#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "Ansibles.mysql"
role "DavidWittman.ansible-redis", github: "DavidWittman/ansible-redis"
role "Stouts.jenkins"
role "Stouts.nginx"
role "Stouts.postfix"
role "Stouts.python"
role "Stouts.rabbitmq"
role "Stouts.sentry"
role "Stouts.sudo"
role "Stouts.supervisor"
role "Stouts.users"
role "lxhunter.apt"
