---
# file: base.yml
- name: Configure all monitor servers (local)
  hosts: local
  connection: local
  gather_facts: False
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  tags: provisioning

  tasks:
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=2678400

- name: Configure all monitor servers
  hosts: launched
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  tags: base
  roles:
    - lxhunter.apt
    - Stouts.users
    - Stouts.sudo
    - Stouts.python
    - Stouts.nginx
    - Stouts.rabbitmq
    - DavidWittman.ansible-redis
    - Stouts.supervisor
    - Ansibles.mysql
    - Stouts.sentry
    - Stouts.jenkins
    - Stouts.postfix

  vars_files:
    - vars.yml

  vars:
    - apt_cache_valid_time: 3600
    - apt_install_recommends: false
    - apt_install_suggests: false
    - apt_install_packages: [
        build-essential,
        git,
        libevent-dev,
        wget,
        python-dev,
        python3-dev
      ]
        
    - python_version: 3.4
    - python_pip_latest:
      - setuptools
      - virtualenv

    - redis_version: "2.8.13"

    - mysql_root_password: "password"
    - mysql_databases:
      - name: "test_database"
        collation: "utf8_general_ci"        # optional, defaults to "utf8_general_ci"
        encoding: "utf8"                    # optional, defaults to "utf8"

    - mysql_users:
      - name: "test_user"
        pass: "password"
        priv: "*.*:ALL"                     # optional, defaults to "*.*:ALL"
        host: "%"

    - users_groups:
        - name: admin
          system: yes
              
    - users_users:
      - name: kf
        groups: admin,sudo
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgCsc6t4IWelotdrrFfxGO/8n7Dqgnsbb4WfXapTFA7Gm0vPKLKT9kHxhVj60E8o4Voqm/RIR9ErxdirtsCh9OZRWS9RKFeMSapwW3w4cvVir4wR5Qy89b1CypshZziInD9Jl3OeJe/jBLYTBHGjJAtKbYNn2TETL+URfjEN0hLQAjTDYf4tju3S9UeIHHRnVLw/42eEW7kXyVT2Wn5Ie20+2kiIR0+L0k/7a0ZH4M1+0UBRGGJEefY7Ab1gniq+bQ9EJUyzMkgOO/lVee7tuvU9NcHaBxH++EHzVkJfZFsoQ0CseC/zE5KJqZ9lTHFbcBVQzOClugA6KWZMv/VQIj 7kfpun@gmail.com 

    - sentry_secret_key: 1LsmGR1DIyCJ5n2bRG5IVOFHdzEPk3KlW0RzxZV39S0vc
    - sentry_hostname: "sentry.{{inventory_hostname}}"

    - jenkins_plugins: [
        "chucknorris",
        "cobertura",
        "dashboard-view",
        "git",
        "greenballs",
        "maven-plugin",
        "violations"]

    - postfix_enabled: no
    - postfix_smtp_sasl_user: myemail@gmail.com
    - postfix_smtp_sasl_password: mypassword

  # tasks:
    # - name: apt-get update
      # apt: update_cache=yes cache_valid_time=2678400

    # - name: Install required system packages.
      # apt: pkg={{ item }} state=installed
      # with_items: "{{ system_packages }}"

    # - name: Install required Python packages.
      # easy_install: name={{ item }}
      # with_items: "{{ python_packages }}"
