---
# file: db.yml
- include: base.yml

- name: Configure all monitor servers
  hosts: launched
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  tags: base
  roles:
    - Stouts.rabbitmq
    - DavidWittman.ansible-redis
    - Ansibles.mysql

  vars:
    - redis_version: "2.8.13"

    - mysql_root_password: "password"
    - mysql_databases:
      - name: "test_database"
        collation: "utf8_general_ci"        # optional, defaults to "utf8_general_ci"
        encoding: "utf8"                    # optional, defaults to "utf8"

    - mysql_users:
      - name: "test_user"
        pass: "password"
        priv: "*.*:ALL"                     # optional, defaults to "*.*:ALL"
        host: "%"
