---
# Effectively lifted from the Ansible documentation on EC2:
# http://docs.ansible.com/ec2_module.html

  - name: Provision an EC2 node
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    vars:
      instance_type: t1.micro
      security_group: sg_thingy
      image: ami-e7b8c0d7
      region: us-west-2
      keypair: ec2
    tasks:
      - name: Launch new Instance
        local_action: ec2 instance_tags="Name=AnsibleTest" group={{ security_group }} instance_type={{ instance_type}} image={{ image }} wait=true region={{ region }} keypair={{ keypair }}
        register: ec2

      - name: Add instance to local host group
        # local_action: add_host hostname={{ item.public_ip }} groupname=launched
        local_action: lineinfile dest="./hosts" regexp="{{ item.public_dns_name }}" insertafter="[launched]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
        with_items: ec2.instances
        #"

      - name: Wait for SSH to come up
        local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
        with_items: ec2.instances

  - name: With the newly provisioned EC2 node configure that thing
    hosts: launched # This uses the hosts that we put into the in-memory hosts repository with the add_host module.
    vars_files:
      - vars.yml
    sudo: yes # On EC2 nodes, this is automatically passwordless. 
    remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
    gather_facts: True  #We need to re-enable this, as we turned it off earlier.
    tags: base
    roles:
      - Stouts.users
      - Stouts.sudo
      - Stouts.python
      - Stouts.nginx
      - Stouts.rabbitmq
      - DavidWittman.ansible-redis
      - Stouts.supervisor
      - Ansibles.mysql
      # - Stouts.sentry
      - Stouts.jenkins

    vars:
      - python_version: 3.4
      - python_pip_latest:
        - setuptools
        - virtualenv

      - redis_version: "2.8.13"

      - mysql_root_password: "password"
      - mysql_databases:
        - name: "test_database"
          collation: "utf8_general_ci"        # optional, defaults to "utf8_general_ci"
          encoding: "utf8"                    # optional, defaults to "utf8"

      - mysql_users:
        - name: "test_user"
          pass: "password"
          priv: "*.*:ALL"                     # optional, defaults to "*.*:ALL"
          host: "%"

      - users_groups:
          - name: admin
            system: yes
                
      - users_users:
        - name: kf
          groups: admin,sudo
          ssh_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgCsc6t4IWelotdrrFfxGO/8n7Dqgnsbb4WfXapTFA7Gm0vPKLKT9kHxhVj60E8o4Voqm/RIR9ErxdirtsCh9OZRWS9RKFeMSapwW3w4cvVir4wR5Qy89b1CypshZziInD9Jl3OeJe/jBLYTBHGjJAtKbYNn2TETL+URfjEN0hLQAjTDYf4tju3S9UeIHHRnVLw/42eEW7kXyVT2Wn5Ie20+2kiIR0+L0k/7a0ZH4M1+0UBRGGJEefY7Ab1gniq+bQ9EJUyzMkgOO/lVee7tuvU9NcHaBxH++EHzVkJfZFsoQ0CseC/zE5KJqZ9lTHFbcBVQzOClugA6KWZMv/VQIj 7kfpun@gmail.com 

      - sentry_secret_key: 1LsmGR1DIyCJ5n2bRG5IVOFHdzEPk3KlW0RzxZV39S0vc
      - sentry_hostname: "sentry.{{inventory_hostname}}"

      - jenkins_plugins: [
          "chucknorris",
          "cobertura",
          "dashboard-view",
          "git",
          "greenballs",
          "maven-plugin",
          "violations"]

    tasks:
      - name: apt-get update
        apt: update_cache=yes cache_valid_time=2678400

      - name: Install required system packages.
        apt: pkg={{ item }} state=installed
        with_items: "{{ system_packages }}"

      - name: Install required Python packages.
        easy_install: name={{ item }}
        with_items: "{{ python_packages }}"
