---
# file: base.yml
- name: Configure all monitor servers (local)
  hosts: local
  connection: local
  gather_facts: False
  sudo: yes
  tags: local

  tasks:
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=2678400

- name: Configure all monitor servers
  hosts: all
  gather_facts: True
  tags: base
  roles:
    - ANXS.build-essential
    - ANXS.postgresql
    - Stouts.apt
    - Stouts.nginx
    - Stouts.nodejs
    - Stouts.python
    - Stouts.rabbitmq
    - Stouts.sudo
    - Stouts.supervisor
    - Stouts.timezone
    - Stouts.users
    - jdauphant.nginx
    - knopki.locale
