---
# file: monitor.yml
- include: base.yml

- name: With the newly provisioned EC2 node configure that thing
  hosts: monitor  # This uses the hosts that we put into the in-memory hosts repository with the add_host module.
  sudo: yes  # On EC2 nodes, this is automatically passwordless. 
  remote_user: ubuntu  # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  # We need to re-enable this, as we turned it off earlier.
  tags: monitor
  roles:
    - Stouts.sentry
    - Stouts.jenkins

  vars_files:
    - vars.yml

  vars:
    - sentry_secret_key: 1LsmGR1DIyCJ5n2bRG5IVOFHdzEPk3KlW0RzxZV39S0vc
    - sentry_hostname: "sentry.{{inventory_hostname}}"

    - jenkins_plugins: [
        "chucknorris",
        "cobertura",
        "dashboard-view",
        "git",
        "greenballs",
        "maven-plugin",
        "violations"
      ]
